
spring.application.name=erp
server.port=${PORT:8083}

# =========================
# DATABASE (supabase)
# =========================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

# =========================
# JPA / HIBERNATE
# =========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# =========================
# LOGGING
# =========================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# ===============================
# SECRET_KEY
# ===============================
jwt.secret=iUX83X2TYeUnVzwnFp181nwmJiGD8ka4jFyp1c8vTMY=